apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - application
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frontend-web
                topologyKey: "kubernetes.io/hostname"
      containers:
       - name: frontend-web    # تأكد إن الاسم هنا هو نفس الاسم ده
          image: us-central1-docker.pkg.dev/gcp-devops-ecommerce/my-registry/frontend-web:84814fdad2b759e1ed0a72d74a2825536dab413a
          ports:
            - containerPort: 80